### ISSUE TITLE
How to calculate BoneKeyFrameTransformRecord of motion data in data preprocessing?

### ISSUE THREAD

**Issue by ZC119** [Carmenw1203/DanceCamera3D-Official#3]

**Comment by Carmenw1203** [comment]
Sorry for the late reply. Actually, we have written some scripts to export the global transform matrix of motion data from VMD files. However, the whole process includes using some complex functions in saba_viewer which means the process is currently semi-automatic.  But we are working on this matter to automatically export the motion data.
