### ISSUE TITLE
For motion visualization in Saba

### ISSUE THREAD

**Issue by shydyl** [Carmenw1203/DanceCamera3D-Official#4]
Thanks for your great work!
I followed the script generating VMD file and I put it into Saba for visualization, but the character did not move, only the camera's perspective changed. How can I visualize the character's motion as well? Can you provide a script to generate a VMD file with motion?

**Comment by Carmenw1203** [comment]
Hi, thank you for your interest in our work. 
I'd like to clarify that we don't generate motion VMD files in our work and we just use the raw VMD motion files directly. You can apply for the dataset through e-mail and you will find a file with download links to download the raw VMD motion files.
