### ISSUE TITLE
Collab with EDGE

### ISSUE THREAD

**Issue by BruceChanceBeatverse** [Carmenw1203/DanceCamera3D-Official#5]
Great work first of all! Super amazing.
So now I input a song into EDGE to generate a dance; what should I do to make your work together with the output of EDGE to integrate into a full dance work with camera movement?

**Comment by Carmenw1203** [comment]
Thank you for your interesting question! Collaborating with EDGE with our model is feasible. The only problem is that the definitions of human motion data in EDGE and our model are different. EDGE uses SMPL data, while our method uses skeletons from MMD resources with 60 frequently used joints. Thus, a retargeting process is needed to align these human motion data formats.
